### ISSUE TITLE
Orders with Vat = 0 still not possible

### ISSUE THREAD

**Issue by henrikvolmer** [mollie/Shopware6#22] opened 2020-05-25 08:12 UTC
Hello everyone, 

unfortunately, I have to reopen an issue concerning Vat. A customer cannot order if he is in a customer group with net prices. 

Steps:
- Assign a customer to the net-prices group
- Order with this customer

1. Problem
The fix from #4 does not work, because the TexStatus is not `tax-free` but `net`

![Bildschirmfoto 2020-05-25 um 10 02 01](https://user-images.githubusercontent.com/25845699/82791881-cfe98400-9e6e-11ea-923b-e3429607765f.png)

2. Problem
Even if the fix of #4 would work, another problem would occur:

![Bildschirmfoto 2020-05-25 um 10 09 48](https://user-images.githubusercontent.com/25845699/82792719-18ee0800-9e70-11ea-858b-c23c5d9b2bb4.png)

with following OrderData:

![Bildschirmfoto 2020-05-25 um 10 11 03](https://user-images.githubusercontent.com/25845699/82792785-358a4000-9e70-11ea-8c2d-5ccf6bd40f5a.png)

**Comment by reindernl** [comment] 2020-05-26 07:16
Can you tell me a little more in-depth what your exact setup is? I'm not fully able te reproduce it, yet. Maybe you could guide me.

**Comment by henrikvolmer** [comment] 2020-05-26 07:33
Actually we don't have a really special setup. 

The ordering country is Germany (regular 19% VAT).
This country is also **not** marked as tax free in the settings.

However, all our customers are in the net customer group (adjustable in the admin). This means that every user also gets net prices displayed in the shop.

Do you have further questions? Ask me specific questions.

**Comment by henrikvolmer** [comment] 2020-05-26 13:04
Did you make any progress here? You need more info? 

Can you already give us a timeline here, when the problem will probably be solved?

**Comment by reindernl** [comment] 2020-05-27 11:43
I use getAmountTotal() on an order entity. I see now that I have to check seperately if the order is a net order and if so, switch to using the function getAmountNet(). This is fixed and will be in the next release.

**Comment by henrikvolmer** [comment] 2020-05-27 11:45
Thanks for the answer. Is it possible to release it now? We need it fast.

**Comment by reindernl** [comment] 2020-05-27 12:09
I'll discuss what's possible.

**Comment by reindernl** [comment] 2020-05-27 16:08
A release is planned for tomorrow 😊

**Comment by reindernl** [comment] 2020-05-28 09:57
@henrikvolmer The new version is released. Please let us know if this works out for you.

**Comment by henrikvolmer** [comment] 2020-05-28 10:42
Sadly not. Now you pay the net price, but you have to pay the brut price.

![Bildschirmfoto 2020-05-28 um 12 40 58](https://user-images.githubusercontent.com/25845699/83131762-aafc4780-a0e0-11ea-9b30-600c5cff7e56.png)

![Bildschirmfoto 2020-05-28 um 12 42 10](https://user-images.githubusercontent.com/25845699/83131769-af286500-a0e0-11ea-9546-b212f896ba1f.png)

**Comment by reindernl** [comment] 2020-05-28 11:22
I have reversed the fix as this was een unintended effect. What I see now is that the calculation of Mollie (which happens in the API call) is different from the data Shopware provides. I can replace Shopware's data by the calculation that Mollie uses, but than (most of the times) the total price doesn't add up. Unfortunately, we have to rethink this.

**Comment by henrikvolmer** [comment] 2020-06-03 06:15
Is there any news on this already?

**Comment by reindernl** [comment] 2020-06-03 12:58
Hi Henrik,

Shopware doesn't save both the gross and net prices on orderline items. Even though they store both these prices on a product. I think that makes it more difficult than it should be.

That being said, there's a built in calculator to calculate the required taxes. But it doesn't always give a result that matches with Mollie's calculation. The Orders API calculates the order to check if everything is acceptable. And I know there's a margin of half a cent at Mollie, but the difference actually is a full cent most of the time in these scenario's. I've asked Mollie if they can raise the margin.

Another thing that is weird to me is that even though the setting for net prices is just to display net prices to these customers, Shopware actually calculates the prices in a whole different way as well. The price including vat on an order of a customer in a group with net prices, is different from the price including vat on the exact same basket of a customer in a group with gross prices.

So we're working on it and are talking things over with Mollie and Shopware.

**Comment by henrikvolmer** [comment] 2020-06-04 09:23
Hi @reindernl,

Thanks for the info. Is there already a timeline for this?

Thanks

**Comment by reindernl** [comment] 2020-06-15 09:33
@henrikvolmer We've released version 1.0.14 of the MolliePayments plugin for Shopware 6 with a bugfix for net orders. Let me know how this works out for you!

**Comment by henrikvolmer** [comment] 2020-06-15 10:29
@reindernl: At first sight it seems to work now. We will now test it in detail and then I will give you a final status.

**Comment by reindernl** [comment] 2020-06-15 12:48
@henrikvolmer Looking forward to that. We've tested quite thoroughly. Testing with a quantity of 11 often gave the above mentioned failure in the previous version of the plugin.

**Comment by KienerNL** [comment] 2020-06-17 12:07
@henrikvolmer Were you able to test in more detail? Any findings?

**Comment by henrikvolmer** [comment] 2020-06-17 12:43
We have not been able to detect any more errors. Thanks for the help

**Closed** 2020-06-17 12:43 UTC
