### ISSUE TITLE
Using Shopware default payment workflow results in payment canceled instead of failed with Shopwware 6.4.5.1

### ISSUE THREAD

**Issue by AndreasA** [mollie/Shopware6#220] opened 2021-10-29 11:13 UTC
You throw a `CustomerCanceledAsyncPaymentException` at two points in your code which automatically triggers the transaction to be canceled by Shopware.

To ensure this isn't a problem, you probably need to differentiate between AsyncFailedPayment exceptions and the canceled

see corresponding shopware code snippet:

```
        try {
            $paymentHandler->finalize($transaction, $request, $context);
        } catch (CustomerCanceledAsyncPaymentException $e) {
            $this->transactionStateHandler->cancel($transactionId, $context->getContext());
            $token->setException($e);
        } catch (PaymentProcessException $e) {
            $this->logger->error('An error occurred during finalizing async payment', ['orderTransactionId' => $transactionId, 'exceptionMessage' => $e->getMessage()]);
            $this->transactionStateHandler->fail($transactionId, $context->getContext());
            $token->setException($e);
        } finally {
            $this->tokenFactory->invalidateToken($token->getToken());
        }
```

you probably also need to avoid to manually change the transaction state in such scenarios.

**Comment by AndreasA** [comment] 2021-11-02 06:38
Might also be an issue in earlier versions already but with you throwing CustomerCanceledAsyncPaymentException the payment is always canceled.

You would probably need to skip the manual order transaction update in such a scenario and just throw the corresponding exception.

**Comment by AndreasA** [comment] 2021-11-02 11:55
The fastest solution would be to check the transaction state and check if it is failed or canceled and throw the corresponding exception at these two points. well probably one point `\Kiener\MolliePayments\Handler\PaymentHandler::finalize` because you capture the that exception there too. I have tried it and it works fine that way as Shopware doesn't do anything if the desired "to" state has already been reached.

**Comment by boxblinkracer** [comment] 2021-11-03 11:58
Hi there

thank you for this
could we start easy by telling me how to reproduce it :)

what do you mean with the shopware default flow?
if the payment fails?

so that means a failed payment with shopware default is accidentally cancelled instead of failed?

thank you

**Comment by AndreasA** [comment] 2021-11-03 12:03
@boxblinkracer Sorry if I wasn't clear before.

But yes.

- Using "Default failed payment" setting in Shopware.
- In test mode, selecting failed payment.

In the end the payment in the order is marked as canceled instead of failed. The issue is that at two points you throw CustomerCanceledAsyncPaymentException which results in Shopware doing the following:

```php
            $this->transactionStateHandler->cancel($transactionId, $context->getContext());
```

**Comment by boxblinkracer** [comment] 2021-11-03 12:27
perfect thank you
so i already had a feeling that something with a status is weird...and it might have been "cancelled".

i havent had time to check out the source code how its done. but maybe you have found that existing problem.

i'll check it out :)
thanks for this

**Comment by boxblinkracer** [comment] 2021-11-03 14:20
Hi

good news on that
currently in development and already solved (at least the first dev-tests pass)
still work in progress

BUT, i was finally able to solve that cypress test
where I already asked why failed payments lead to cancelled...we thought thats just how it is :) 

https://github.com/mollie/Shopware6/pull/226

**Comment by AndreasA** [comment] 2021-11-03 16:06
@boxblinkracer Great. Looks like it should indeed solve it at a first glance.

**Comment by boxblinkracer** [comment] 2021-11-08 13:43
Hi
this has been fixed with 1.5.6 today
failed payments are now really "failed" instead of cancelled

please note, that there are still some status-transitions that i'm not that happy with
but i couldnt fix this with the current release yet
.we have internal tickets to go through it again

thanks for your help
i would now close this ticket

**Closed by boxblinkracer** 2021-11-08 13:43 UTC
Labels: Bug, On Roadmap

**Comment by AndreasA** [comment] 2021-11-08 15:03
@boxblinkracer Great. How long does it take for the new release to be available in packagist?

**Comment by boxblinkracer** [comment] 2021-11-08 15:42
should be updated by now. do you see it?

**Comment by AndreasA** [comment] 2021-11-08 15:43
@boxblinkracer Yes. thanks.

**Comment by boxblinkracer** [comment] 2021-11-08 15:49
perfect. thx for the feedback

**Comment by AndreasA** [comment] 2021-11-08 16:02
@boxblinkracer I just noticed one minor issue but I think it is unrelated to this change, if one sets `Order state with a failed transaction` to `Canceled` then a failed payment results in action  `fail` not allowed.

I just set this to `Skip this state` now and it works. But maybe some warning / help text could be useful ?

**Comment by boxblinkracer** [comment] 2021-11-08 17:37
hi

where do you set this? in the admin?

**Comment by AndreasA** [comment] 2021-11-08 18:31
@boxblinkracer Hi, no I got the error on the payment finalize page in Storefront.

But I need to re-check because it is possible that it is actually project specific because if I remember correctly there is an event listener that cancels an open payment, if the order itself is canceled which would be the case in this scenario.

I will check it tomorrow but most likely that is the issue. So I think everything is fine from the plugin itself but I need to verify.
In any case due to such state listeneres using Skip this state is fine for that project anyway.

**Comment by boxblinkracer** [comment] 2021-11-08 19:24
hi
weird. but i think it might be project related. 
it has been tested in 11 shopware versions. 
but what i can say is, in addition to this i had a live testing server that had a similar problem. 
db was screwed. really dont know why but the shopware authorized state was missing. translations there but state and transitions not. 
the server is actually nothing special. added it again in db as in the same default version and it worked again. 

besides that the whole transition stuff will be redone anyway. too different. i also know other "bugs" or things that could be better that are by design at the moment. but for now it should be fine

**Comment by AndreasA** [comment] 2021-11-09 07:45
@boxblinkracer Just to let you know. It was indeed project specific as I expected. So everything is fine regarding the mollie plugin.

Great work. Thanks for the fix.
