### ISSUE TITLE
Javascript always using test mode regardless of configuration

### ISSUE THREAD

**Issue by dl-mbegerau** [mollie/Shopware6#27] opened 2020-06-11 19:20 UTC
### Environment
OS: Ubuntu 18.04
Apache: 2.4.29
PHP: 7.3.17
MySQL: 5.7.30
Shopware: 6.2.0 (fresh installation from production repository)
Mollie: 1.0.13
Other Plugins: Shopware 6 Demo data (1.0.5)

### Problem
Regardless of the configuration settings, the mollie javascript plugin always assumes that it's in test mode.

_image: Test mode is turned off in Mollie plugin configuration_
![test-mode-off](https://user-images.githubusercontent.com/57012534/84423288-d3596b00-abe3-11ea-9c21-5ae6f41c13e3.png)
_image: The js plugin states that test mode is on_
![js-test-mode-on](https://user-images.githubusercontent.com/57012534/84423356-ef5d0c80-abe3-11ea-83c5-ee0e5b6993c7.png)

### Detected causes
The configuration values are send as string types.
src/Resources/views/storefront/component/payment/payment-fields.html.twig
```
17        <div id="mollie_components_credit_card"
18             class="mollie-components-credit-card d-none"
19             data-customer-id="{{ context.customer.id }}"
20             data-profile-id="{{ page.mollie_profile_id }}"
21             data-locale="{{ page.mollie_locale }}"
22             data-shop-url="{{ seoUrl('frontend.home.page') }}"
23             data-test-mode="{{ page.mollie_test_mode }}">
```
src/Resources/app/storefront/src/mollie-payments/plugins/creditcard-components.plugin.js
```
23            let locale = container.getAttribute('data-locale');
24            let profileId = container.getAttribute('data-profile-id');
25            let shopUrl = container.getAttribute('data-shop-url');
26            let testMode = container.getAttribute('data-test-mode');
```
The `testMode` variable is saved as 'true' or 'false' strings (not as boolean). In both cases javascript interpretes it as `true` because any non-empty string is `true` for javascript.

### Solution suggestion
1. Manually change 'false' to `false` in your javascript or `eval` it (not recommended). Or add an `{% if %}` to your twig and only add the attribute if test mode is active.

2. How Shopware intended it:
In Shopware 6 every plugin automatically populates the `options` property with an object from a data attribute from html.

First step: Initialize your plugin only when needed. Right now you register your plugin like this:
custom/plugins/MolliePayments/src/Resources/app/storefront/src/main.js
```
8 // Register them via the existing PluginManager
9 const PluginManager = window.PluginManager;
10 PluginManager.register('MollieCreditCardComponents', MollieCreditCardComponents);
11 PluginManager.register('MollieIDealIssuer', MollieIDealIssuer);
```
You are not defining a selector (third parameter) so the plugin gets initiated on `document` by default. So it gets initiated on every page of the shop. You should initiate your plugins on a selector pointing to the id or class of the payment method (also import the PluginManager):
```
8 // Register them via the existing PluginManager
9 import PluginManager from 'src/plugin-system/plugin.manager';
10 PluginManager.register('MollieCreditCardComponents', MollieCreditCardComponents, '#mollie_components_credit_card');
11 PluginManager.register('MollieIDealIssuer', MollieIDealIssuer, '.mollie-ideal-issuer');
```
This has two advantages. First, the plugins only initiate in the checkout. So you can remove some of the conditions in your script. Second, Shopware now will automatically parse the data attributes. The data attribute has to use exactly this format `data-<js-plugin-name>-options` (uppercase converted to hyphen+lowercase). In your case: `data-mollie-credit-card-components-options`.

So it would look like something like this:
src/Resources/views/storefront/component/payment/payment-fields.html.twig
```
17        <div id="mollie_components_credit_card"
18             class="mollie-components-credit-card d-none"
19             data-mollie-credit-card-components-options='{
20                "customerId": "{{ context.customer.id }}",
21                "profileId": "{{ page.mollie_profile_id }}",
22                "locale": "{{ page.mollie_locale }}",
23                "shopUrl": "{{ seoUrl('frontend.home.page') }}",
24                "testMode": {{ page.mollie_test_mode }}
25             }'
```
Now in your js plugin `this.options` will contain the object defined in twig. The `testMode` property is boolean because it's not enclosed by quotes in twig. No need for any of the `getAttribute` lines, you can use `this.options.testMode` or `this.options.locale`. Also `this.el` references to the element the plugin was initiated on. So you can use `this.el` instead of `container`.

You can also set default values by declaring the option property at the beginning of your js plugin:
```
3 export default class MollieCreditCardComponents extends Plugin {
4   options = {
5     testMode: true
6   }
```

**Comment by julian-kiener** [comment] 2020-06-17 06:26
Hello Malte,

Can you check if version 1.0.14 fixed this for you?

**Comment by dl-mbegerau** [comment] 2020-06-17 14:12
I will test it this week. Right now, I'm a bit busy with other stuff.

**Comment by dl-mbegerau** [comment] 2020-06-26 16:24
Hey,
I just tested it with Shopware 6.2.2 and Mollie 1.0.15:

The error still remains. Maybe the fix got lost somewhere, because I checked the payment-fields.html.twig and the creditcard-components.plugin.js and in both files there is no change regarding this problem. The testMode variable is still filled with a string value instead of a boolean.

_image: the testMode constant is filled with the string "false" but Javascript interprets it as `true` (see console) because it's not an empty string_
![testmode-value-string](https://user-images.githubusercontent.com/57012534/85879174-80fd7a00-b79f-11ea-963f-16594b9e6183.png)

Please, reread my original post and consider using the second solution suggestion I proposed. I know, it may seem complicated on the first look, but it actually makes live easier if you apply it and this will make your plugin much more compliant with the way Shopware expects Javascript to be used. Or at least apply the first suggestion if you want a quick solution.

**Comment by reindernl** [comment] 2020-06-29 13:08
I'm actually working on the approach with the options variable. It works for like 90%, but somehow the options are empty again later in the process. I can't seem to find out why that is.

**Comment by dl-mbegerau** [comment] 2020-06-29 13:21
Hey, this sounds weird. Seems like it's a different initialization of the class if it has different properties. Is it possible that the plugin gets re-initiated, maybe when the payment modal opens? If that is a problem you could add or remove a class or otherwise ensure that the initiate selector does not find the element if it's already initiated.

What do you mean by "later in the process", when does this happen? Sorry, I can't really help you right now. Too much to do...

**Comment by reindernl** [comment] 2020-06-29 13:38
'Later in te process' means on an event listener. But I think I figured it out already. Seems like options should be static, although the functions aren't static. Feels a bit weird. But as far as I can see, this solves it. Will test some more.

**Comment by reindernl** [comment] 2020-06-29 14:36
I've finished the work. I also fixed the form being submitted even though there are errors. The form is submitted through Ajax, so my event.preventDefault() wasn't doing anything, as the form was never submitted in the regular way. I know prevent the submit button from being clicked, do my checks and submit the form. This works well.

Mollie Components is now also a javascript plugin in stead of a separately loaded js file. So that's way cleaner. It's in our review process now, expected to release later this week.

**Comment by reindernl** [comment] 2020-07-13 14:02
Have you tried the latest version?

**Comment by dl-mbegerau** [comment] 2020-07-13 14:30
Hey, I saw the release but I couldn't test it yet. Maybe this week. Probably next week.

**Comment by reindernl** [comment] 2020-07-27 11:42
It seems like the issue is fixed, so I'll close this topic. If issues still occur, feel free te open a new topic.

**Closed by reindernl** 2020-07-27 11:42 UTC
