### ISSUE TITLE
Possible issues with higher price precisions

### ISSUE THREAD

**Issue by azngeek** [mollie/Shopware6#439] opened 2022-10-12 13:16 UTC
**Current state**

We have a merchant where the products have a high decimal precision. In that case we do have 6 decimal places. 

![image](https://user-images.githubusercontent.com/213429/195350934-7fc88b7e-f397-4b5f-9391-6dcc08466e51.png)

**Error description**

We could see that an error occurs during the checkout, for example if you try to use the credit card, which says something like:

> "The amount of the order does not match the total amount from the order lines. Expected order amount to be €14.81 but got €14.82."

So based on this error, we assume that the expected **authorized** amount and the final **charged** amount might not be equal.

**Reconstruction**

This is an actual order where the error occured. Some assumptions. 

1. The system is configured that an article does have a higher decimal precision. In this case 6 decimal places.
2. Do have some articles :)

You could see that base on the following table, the expected amount should be **€14.81**. This is also stated in the exception.
You could also see that based on our assumption the possible calculated value is **€14,82** when calculated with a higher precision.

This leads to the conclusion that the values transfered to Mollie do have a lower precision or Mollie is not able to calculate with higher decimal places. The final part will contain some logs where you can actually see that in the first instance the items are not transferred with their original value but the rounded one.

Position |  Shopware 6 value | without round | round on 2 decimal places
-- | -- | -- | --
5x DIN 963 | 2,7336 | 2,7336 | 2,73
5x DIN 985 | 2,9334 | 2,9334 | 2,93
5x DIN 125 A | 1,6494 | 1,6494 | 1,65
Shipping | 7,50 | 7,50 | 7,50
Total | 14,82 (round) | 14,1864 | 14,81

**Log**

As you can see in the log, we assume that the error happens because the amount transmitted for every line item is not the original but the rounded value.

`ApiException(code: 422): [2022-10-11T16:38:06+0000] Error executing API call (422: Unprocessable Entity): The amount of the order does not match the total amount from the order lines. Expected order amount to be €14.81 but got €14.82. Documentation: https://docs.mollie.com/overview/handling-errors. Request body: {\"amount\":
{\"currency\":\"EUR\",\"value\":\"14.82\"}
,\"locale\":\"de-AT\",\"method\":\"creditcard\",\"orderNumber\":\"450078\",\"payment\":{\"webhookUrl\":\"https:\\/\\/www.frantos.com\\/at\\/mollie\\/webhook\\/1f45e063a516479786bc9bd9e855ed8d\",\"cardToken\":\"tkn_NwspRhvspR\"},\"redirectUrl\":\"https:\\/\\/www.frantos.com\\/at\\/mollie\\/payment\\/1f45e063a516479786bc9bd9e855ed8d\",\"webhookUrl\":\"https:\\/\\/www.frantos.com\\/at\\/mollie\\/webhook\\/1f45e063a516479786bc9bd9e855ed8d\",\"lines\":[{\"type\":\"physical\",\"name\":\"DIN 963 Senkschraube mit Schlitz 4.8 verzinkt M 5x25\",\"quantity\":5,\"unitPrice\":
{\"currency\":\"EUR\",\"value\":\"0.55\"}
,\"totalAmount\":{\"currency\":\"EUR\",\"value\":\"2.73\"},\"vatRate\":\"20.00\",\"vatAmount\":{\"currency\":\"EUR\",\"value\":\"0.46\"},\"sku\":\"1052\",\"imageUrl\":\"https%3A%2F%2Fstatic.frantos.com%2Fmedia%2F39%2F29%2F95%2F1664458060%2FTI-38_B_4.PNG\",\"productUrl\":\"\",\"metadata\":{\"orderLineItemId\":\"31ed2121ace3470fb2a3ff694539ab44\"}},{\"type\":\"physical\",\"name\":\"DIN 985 Stoppmutter Stahl 8 verzinkt M 5\",\"quantity\":5,\"unitPrice\":
{\"currency\":\"EUR\",\"value\":\"0.59\"}
,\"totalAmount\":{\"currency\":\"EUR\",\"value\":\"2.93\"},\"vatRate\":\"20.00\",\"vatAmount\":{\"currency\":\"EUR\",\"value\":\"0.49\"},\"sku\":\"4028\",\"imageUrl\":\"https%3A%2F%2Fstatic.frantos.com%2Fmedia%2F74%2Fd0%2F9f%2F1664458095%2FTI-67_B_1.PNG\",\"productUrl\":\"\",\"metadata\":{\"orderLineItemId\":\"d5c7adba109848deaac7f03574ee1c77\"}},{\"type\":\"physical\",\"name\":\"DIN 125 A Scheiben Stahl verzinkt M 5 
u00d8 5,3x10x1\",\"quantity\":5,\"unitPrice\":
{\"currency\":\"EUR\",\"value\":\"0.33\"}
,\"totalAmount\":{\"currency\":\"EUR\",\"value\":\"1.65\"},\"vatRate\":\"20.00\",\"vatAmount\":{\"currency\":\"EUR\",\"value\":\"0.28\"},\"sku\":\"48545\",\"imageUrl\":\"https%3A%2F%2Fstatic.frantos.com%2Fmedia%2F9d%2Fb7%2F1b%2F1664458132%2FD00125_A_AK.JPG\",\"productUrl\":\"\",\"metadata\":{\"orderLineItemId\":\"83ec8edda73845e2acfd4e1ae8c91dad\"}},{\"type\":\"shipping_fee\",\"name\":\"Delivery costs 1\",\"quantity\":1,\"unitPrice\":
{\"currency\":\"EUR\",\"value\":\"7.50\"}`

**Comment by boxblinkracer** [comment] 2022-10-12 17:17
Hi

perfect for this.
so with the rounding we are quite experienced by now. :D 
sounds weird but it is the same as with Shopware 5 back then

Mollie only allows a special rounding, so our task is "just" to prepare the data for Mollie so that their cross checks match along with the final total amount that the customer sees in the shop as final sum and has to pay

so all we need is the line items and some settings in the shop, so that we can reproduce and adjust the calculation for these cases, until no more such "edge" cases exist.
we also create some unit tests for it ;)

so thank you so much for this detailed issue
i'll make sure it gets done :)

**Comment by azngeek** [comment] 2022-10-25 09:13
Can we have a Feedback on this topic? It is a critical issue for us, as our customer has to deal with this every day and manually fix the invoices in his ERP.

**Comment by boxblinkracer** [comment] 2022-11-02 09:10
hi
im already working on it
problem is that shopware rounds 14,8164 to 14,82 which is used as total for mollie, because you always want to ensure the displayed shopware price is paid in the end.
mollie should actually allow a cent off, so i'm wondering why this is not the case anymore

**Comment by boxblinkracer** [comment] 2022-11-28 16:13
the next version has a custom rounding configuration that prevents these problems.
in fact, there are more troubles with rounding, if e..g one uses a grand-total interval of xyz :)
then line items might be 14,80, but the grand total is 15,00 of Shopware :)

**Comment by boxblinkracer** [comment] 2023-02-03 15:09
Hi
the rounding feature has been released in v3.4.0

**Closed by boxblinkracer** 2023-02-03 15:09 UTC
Labels: Bug, Feature Request, Fixed and ready for next release

**Comment by azngeek** [comment] 2023-02-03 16:09
Fantastic!
