### ISSUE TITLE
Error executing API call (422: Unprocessable Entity): The metadata storage is currently limited to 1024 bytes.

### ISSUE THREAD

**Issue by MelvinAchterhuis** [mollie/Shopware6#348] opened 2022-05-05 15:35 UTC
When refunding multiple line-items the request body exceeds the limit of 1024kb that is set by Mollie. 

Example of the request:

```
[2022-04-22T07:40:56.262768+00:00] Mollie.INFO: Starting refund for order: xxxx (Session: ...) {"session":"","processors":{"uid":{"uid":"xxxx"},"web":{"url":"/api/_action/mollie/refund","ip":"xxxx","http_method":"POST","server":"xxxx","referrer":"xxxx"}}} []
[2022-04-22T07:40:56.469951+00:00] Mollie.ERROR: [2022-04-22T07:40:56+0000] Error executing API call (422: Unprocessable Entity): The metadata storage is currently limited to 1024 bytes. Documentation: https://docs.mollie.com/overview/handling-errors. Request body: {"description":"Refunded through Shopware. Order number: xxxxx","metadata":"{\"type\":\"full\",\"composition\":[{\"swLineId\":\"xxxxx\",\"mollieLineId\":\"odl_1.g38zya\",\"swReference\":\"xxxxx\",\"quantity\":1,\"amount\":55},{\"swLineId\":\"xxxxx\",\"mollieLineId\":\"odl_1.aut0sc\",\"swReference\":\"xxxxx\",\"quantity\":1,\"amount\":50},{\"swLineId\":\"xxxxx\",\"mollieLineId\":\"odl_1.s8j692\",\"swReference\":\"xxxxx\",\"quantity\":1,\"amount\":50},{\"swLineId\":\"xxxxx\",\"mollieLineId\":\"odl_1.y6sus8\",\"swReference\":\"xxxxx\",\"quantity\":1,\"amount\":25},{\"swLineId\":\"xxxxx\",\"mollieLineId\":\"odl_1.h1tcj2\",\"swReference\":\"xxxxx\",\"quantity\":1,\"amount\":24},{\"swLineId\":\"xxxxx\",\"mollieLineId\":\"odl_1.m59j3o\",\"swReference\":\"xxxxx\",\"quantity\":1,\"amount\":45},{\"swLineId\":\"xxxxx\",\"mollieLineId\":\"odl_1.4ribey\",\"swReference\":\"xxxxx\",\"quantity\":1,\"amount\":21}]}","lines":[{"id":"xxxxx","quantity":1},{"id":"xxxxx","quantity":1},{"id":"xxxxx","quantity":1},{"id":"xxxxx","quantity":1},{"id":"xxxxx","quantity":1},{"id":"xxxxx","quantity":1},{"id":"xxxxx","quantity":1}]}. Field: metadata (Session: ...) {"session":"","processors":{"uid":{"uid":"ff4b4b9"},"web":{"url":"/api/_action/mollie/refund","ip":"xxxxx","http_method":"POST","server":"xxx","referrer":"xxxx"},"introspection":{"file":null,"line":null,"class":"Kiener\\MolliePayments\\Controller\\Api\\RefundController","function":"refundAction"}}} []
```

This results in a successful refund, however the refunded line items are not passed on to Mollie and external ERP integrations can't fetch the returned line items via API.

See also https://github.com/mollie/Shopware6/issues/330#issuecomment-1106186618 what we see in the refund manager when refund is successful, but line items failed because of the request body being to large.

**Comment by boxblinkracer** [comment] 2022-05-11 09:02
Hi

thanks for this
I'm indeed aware of this at the moment (i dont know if i already responded you somewhere else).
Problem is that there is a maximum in the metadata that I wasn't aware of.
So my question is, ist this an edge case...because it would mean that a lot of items are included in a single refund.
I would need to know how many items are in there so I can see how likely this problem is.

In the meantime, it should be possible by creating 2 separate refunds. Then everything should work.

I also have various ideas about a solution, just like a compression of the metadata JSON that I am creating in the plugin.
That could even cut it down to 50-60% percent, which should be enough I think (depends on the item count you respond with to my question)

**Comment by MelvinAchterhuis** [comment] 2022-05-12 06:39
@boxblinkracer ,

Merchant of ours is in the fashion industry where customers sometimes have the habit to order everything in two sizes and return the items that don't fit. So it doesn't seems like an edge case for me. I've proposed the separate refund workaround for now.

**Comment by boxblinkracer** [comment] 2022-05-12 07:32
yeah sorry, edge case speaking of the number of items,
because i still dont know if we are talking about 5 items or 15 items :D 
so any number would help me to figure out how big the problem is

**Comment by MelvinAchterhuis** [comment] 2022-05-12 07:44
Example in opening post has 7 line items refunded

**Comment by boxblinkracer** [comment] 2022-05-17 10:09
Hi Melvin
alright thank you
so current plan is, at the moment it's necessary to split it because of the maximum metadata size.
I did already have an internal discussion about a metadata-compression algorithm. so we will do it, which could shrink the data for about 30%. it will never go away until mollie increases the size, but we can try to make the problem as "edge-case" as possible :)

**Comment by MelvinAchterhuis** [comment] 2022-05-25 11:32
@boxblinkracer , do you have an ETA when this solution is implemented?

**Comment by boxblinkracer** [comment] 2022-06-27 07:22
Hi @MelvinAchterhuis 
sorry i didnt see this (it was during my vacation)
its planned for 2.4. i'm currently working on the huge release 2.3, and afterwards we go for a smaller 2.4 (around end of july i think) with this included
is that ok for you?

**Comment by MelvinAchterhuis** [comment] 2022-08-26 10:56
@boxblinkracer 
This seems to solve the issue!

**Comment by boxblinkracer** [comment] 2022-08-26 11:55
YES @MelvinAchterhuis 
thank you so muchk, so ready to merge haha

**Comment by boxblinkracer** [comment] 2022-09-01 20:53
compression of data released in v2.5

**Closed by boxblinkracer** 2022-09-01 20:53 UTC
Labels: Bug

**Comment by ChristopherDosin** [comment] 2022-09-09 08:20
@boxblinkracer Because the size is just reduced: We would still run into issues when the return is too big even for the reduced ones.

In our case: We can only refund about aprox. 4 lineItems at once. ( We didn't test the max. amount yet with the new update ). However: The initial issue will remain i guess.

For the future it would be great to know if Mollie can't just increase the allowed size for the meta storage?

**Comment by boxblinkracer** [comment] 2022-09-12 14:04
i heard of 7 items with the previous version, and now it has to be more
so i'm wondering why it should only be 4 for you?

mollie has already been requested to increase it, though i dont have more information or access on that

also this is only for line item based refunds from the refund manager, and only if it's not possible for a merchant to split it into 2 refunds...so very edgi cases usually....

if we have still real troubles let me know then I will try to create a different mode maybe :)

**Comment by MelvinAchterhuis** [comment] 2023-02-06 13:05
> mollie has already been requested to increase it, though i dont have more information or access on that

@boxblinkracer ,
any update on this?

**Comment by MelvinAchterhuis** [comment] 2023-05-15 11:01
@boxblinkracer ,
any update on this?
