### ISSUE TITLE
PaymentController - Uses default router - does not produce correct storefront URLs?

### ISSUE THREAD

**Issue by AndreasA** [mollie/Shopware6#40] opened 2020-11-05 13:57 UTC
Maybe I did something wrong but the PaymentController uses the symfony default router and therefore ignores the URLs of the sales channel. 

This results in an URL which misses the Storefront configuration for the URL. So it always points to  `/`.

**Comment by AndreasA** [comment] 2020-11-05 13:58
The same for the webhook controller.

**Comment by milan-kiener** [comment] 2020-11-16 08:57
Hi @AndreasA, could you elaborate on this issue? As far as we can see, this is expected behaviour. In what situation would you have no store configured? Or do you refer to using the headless setup?

**Comment by AndreasA** [comment] 2020-11-16 13:15
Hi @milan-kiener, no this is not headless related. The issue is that the router you use, might not provide the correct URL for the store.

Your code uses the following service definition:
```
<service id="Kiener\MolliePayments\Storefront\Controller\PaymentController" public="true">
            <argument type="service" id="router.default"/>
```

this means you use the Symfony default router and not the Shopware / Storefront modified version like e.g. used by Shopware here:
```
<service id="Shopware\Core\System\User\Recovery\UserRecoveryService">
            <argument type="service" id="user_recovery.repository"/>
            <argument type="service" id="user.repository"/>
            <argument type="service" id="router"/>
            <argument type="service" id="Shopware\Core\Framework\Event\BusinessEventDispatcher"/>
        </service>
```


This results in URLs looking like this:
`https://www.example.com/mollie/...`
instead of e.g. 
`https://www.example.com/de-de/mollie/...`

It will work as long as I do not need any other specific URLs for the current store / language / currency.

At least during my tests this was the result.

**Comment by AndreasA** [comment] 2020-11-16 13:18
Btw. I adjusted the description above. Not sure why I wrote it like this at that time 😄

**Comment by milan-kiener** [comment] 2020-11-19 08:45
@AndreasA This is work in progress for the upcoming release (in the week after Black Friday)

**Comment by milan-kiener** [comment] 2020-12-10 08:11
@AndreasA We decided to rewrite a part of the plugin to have a solid support for headless. We expect this to release in January. We will keep you posted on this.

**Comment by milan-kiener** [comment] 2021-02-11 16:30
@AndreasA This issue seems to be not headless related. This one should be resolved with our latest release.

**Closed by milan-kiener** 2021-02-11 16:30 UTC
