### ISSUE TITLE
Flow Builder: Mail Templates not assignable to events

### ISSUE THREAD

**Issue by LouisEiermann** [mollie/Shopware6#408] opened 2022-08-24 14:40 UTC
At the moment only the trigger "Renewal Reminder" lets you assign a mail sending event. The other 4 triggers (p.e. "Started") do not let you assign a mail event. How can we send mails on these other triggers? Especially starting and cancelling are very relevant to customers.

**Comment by azngeek** [comment] 2022-08-25 11:28
I guess this is a duplicate of https://github.com/mollie/Shopware6/issues/385?

**Comment by boxblinkracer** [comment] 2022-08-25 12:21
Hi

thanks for this

yes duplicate and good thing...already developed and coming with one of the next releases :)

https://github.com/mollie/Shopware6/pull/405

**Comment by boxblinkracer** [comment] 2022-08-31 10:31
released in version 2.5

**Closed by boxblinkracer** 2022-08-31 10:31 UTC
Labels: Duplicate, Reproduced and Ready for Release
