### ISSUE TITLE
Process for partial refunds with Klarna pay later

### ISSUE THREAD

**Issue by azngeek** [mollie/Shopware6#234] opened 2021-11-10 09:31 UTC
**How to do a partial refund for Klarna pay later**

I have a customer who ordered 2 Items. The customer payed with Klarna Pay Later. For example:

1. Item A : 100
2. Item B: 150

Total: 250

**Check for items in ERP**

The customer checked, if the items are available in the ERP and unfortunately there was an error so we could not sell Item B. What we want to do now is to refund Item B, so that the customer will not have to pay 250 but only 100. So updating the invoice. 

How is this possible?

**Comment by boxblinkracer** [comment] 2021-11-10 12:50
Hi @azngeek 

thank you for your message

so the 100 can be easily refunded inside the order in the Shopware Administration
here is a guide on how to do this
https://github.com/mollie/Shopware6/wiki/Refunds

this can also be done inside the Mollie Dashboard.

the "Ship through Mollie" features directly next to the line item in the administration is a legacy feature I think and might not work as expected (just found that a few days ago)

but the thing written above should help you i think
so this is also the most important thing, to satisfy the customer and give him his money

the update of the invoice is a plain shopware thing
so you might just need to remove that line item in there, or set it as cancelled...

let me know if this helps you

**Comment by boxblinkracer** [comment] 2022-02-15 09:38
Hi

I just wanted to reach out and ask if the above did help you?
in addition to this, v2.0 brought back Ship through Mollie for single line items and way more features.

**Comment by azngeek** [comment] 2022-02-17 17:14
**Current state**

The refund-feature does not work as expected as you can only refund a dynamic amount but not a specific item. We need to be able to keep a reference of the refunded amount to the any line item in the order. 

However this is something which we now understand will be solved in the future by Shopware when a sort of `PaymentRefundHandlerInterface` is implemented. In the meanwhile this ticket can be closed.

**Comment by boxblinkracer** [comment] 2022-02-17 17:28
Hi

yes and no
so the reason why the refund is only based on the amount is the problem with promotions.

lets imagine you have a promotion, buy 3 t-shirts and get 1 OFF...(2 x 10 EUR = 20 EUR)
now the customer returns 1 t-shirt...what do you do? refund 10 EUR, refund (20/3) EUR...refund nothing because its the free one?...so really depends

technically the problem is. mollie has 2 line items...1 with t-shirts (qty 3 and amount 20) and 1 promotion with amount -10 EUR. so that means we need to combine providing a custom amount and somehow telling Mollie what items and quantities will be done. so we need to see what we can come up with :)

the Shopware solution itself however might not be the final-solution for this...but maybe it helps :)
also...we have something planned ;)

**Comment by azngeek** [comment] 2022-02-17 18:22
Haha okay. This is the parameter we also use for the ERP-exports 👍  

So should we keep this ticket opened until the composition-integration is done? We would also alpha/beta-test it :)

**Comment by boxblinkracer** [comment] 2022-02-17 23:09
:) great that you use it, makes me happy, thats why it exists

yeah..I think we can keep it open for now :)
and thanks, I'll try to reach out if necessary

**Comment by boxblinkracer** [comment] 2022-03-24 16:24
theres a new refund manager available now
does it solve this issue? because i think so? then i would close this ticket @azngeek  ?

**Closed** 2022-04-06 22:01 UTC
Labels: Released
